export const TERMS_CONDITIONS = `CAR FLO TERMS OF USE AGREEMENT 

Last updated on August 28, 2018

Welcome to Car Flo ("Car Flo," "we," or "our").

By using the website located at carflo.co and any subdomains thereof, as well as the related mobile websites, the mobile application called Car Flo (the “App”), and the service provided thereon (collectively, the “Service”), you agree to be bound by these Terms of Use (this “Terms of Use” or “Agreement”), whether or not you register as a member of Car Flo ("Member"). If you wish to become a Member and/or make use of the Service, please read this Agreement. If you object to anything in this Agreement or the Car Flo Privacy Policy, do not use the Service. 
	
PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS, INCLUDING VARIOUS LIMITATIONS AND EXCLUSIONS, AND A DISPUTE RESOLUTION AND CLASS ACTION WAIVER CLAUSE THAT GOVERNS HOW DISPUTES WILL BE RESOLVED.

1. Electronic Agreement. This Terms of Use is an electronic contract that sets out the legally binding terms of your use of the Service. This Terms of Use is subject to change by Car Flo at any time, effective upon posting on the Service. By accessing and/or using the Service or becoming a Member, you accept this Terms of Use and agree to the terms, conditions and notices contained or referenced herein. Your continued use of the Service following Car Flo’s posting of revised terms of any section of the Terms of Use will constitute your express and binding acceptance of and consent to the revised Terms of Use.

2. Access and Retention. In order to access and retain this electronic Agreement, you must have access to the World Wide Web, either directly or through devices that access web-based content, and pay any service fees associated with such access. In addition, you must use all equipment necessary to make such connection to the World Wide Web, including a computer and modem or other access device. Please print a copy of this document for your records. To retain an electronic copy of this Agreement, you may save it into any word processing program.

3. Eligibility. You must be at least eighteen (18) years of age to use the Service. By using the Service, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement.

The Service is also not available to any users who have been previously removed or suspended from the Service. 

By using the Service, you represent and warrant that you have the right, authority and capacity to enter into this Terms of Use and to abide by all of the terms and conditions of this Terms of Use.

4. License for Mobile Application

Car Flo grants you, subject to your compliance with these Terms of Use, a limited, non-exclusive, non-transferable license to download and install a copy of the App. You may download the App on a single device (whether mobile or otherwise) to which you have exclusive control. We reserve all rights in and to the App which are not expressly granted to you under these Terms of Use. You are prohibited from running any version of the App on a jailbroken device.  You acknowledge and agree that new or updated versions of the App may include new or updated Terms of Use. Because new or updated versions of the App may include enhanced security or fixes to previous security-related problems, the failure to install the new version of the App may expose you to security risks, including without limitation a breach of your personal information.

5. Commercial Use of Service. 
If you are using and/or accessing the Service on behalf of a company, entity, or organization (collectively, a “Subscribing Entity”), you represent and warrant that:

a. You are an authorized representative of the Subscribing Entity, and that you have the authority to bind the Subscribing Entity to this Terms of Use;
b. You have read and understand this Terms of Use; and
c. You agree to this Terms of Use on behalf of the Subscribing Entity.

Illegal and/or unauthorized uses of the Service include, but are not limited to, collecting usernames and/or email addresses of Members by electronic or other means for the purpose of sending unsolicited email, unauthorized framing of or linking to the Service, sharing or disclosing your username or password to any third party or permitting any third party to access your account, attempting to impersonate another user or person, use of the Service in any fraudulent or misleading manner, any automated use of the system, such as scraping the Service, automated scripts, spiders, robots, crawlers, harvesting or data mining tools or the like, interfering with, disrupting, or creating an undue burden on the Service or the networks or services connected to the Service, and using the Service in a manner inconsistent with any and all applicable laws and regulations. Illegal and/or unauthorized use of the Service may be investigated, and appropriate legal action may be taken, including without limitation, civil, criminal, and injunctive redress. Use of the Service is with the permission of Car Flo, which may be revoked at any time, for any reason, in Car Flo’s sole discretion.

6. Account Creation and Security. You are responsible for maintaining the confidentiality of the username and password that you designate during the registration process, and you are fully responsible for all activities that occur under your username and password. You agree to (a) immediately notify Car Flo of any unauthorized use of your username or password or any other breach of security, and (b) ensure that you exit from your account at the end of each session. Car Flo will not be liable for any loss or damage arising from your failure to comply with this provision. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. If you share your computer with others, you may wish to consider disabling your auto-sign in feature if you have it linked to your Car Flo account. 

In creating and maintaining your account, you agree to provide accurate information to us at all times. In the event that you discover that you have provided inaccurate or misleading information, you agree to immediately correct such information. If you use an alias as your account name, you agree not to use an alias that is vulgar, defamatory, offensive, or that violates any third party’s intellectual property rights or otherwise violates these Terms of Use or the Car Flo Privacy Policy.

7. Your Use of the Service

a. If you are a driver for Uber, Lyft, and/or another rideshare service (each, a “Rideshare Service”), you will ensure that you will comply at all times with the Terms of Use, Privacy Policy, or any other contractual agreement with such Rideshare Service (collectively, the “Rideshare Terms”), and that your use of the Service will comply at all times with such Rideshare Terms. You acknowledge and agree that Car Flo is not responsible for ensuring that the Service complies with any such Rideshare Terms, and that Car Flo is not responsible for your violation of such Rideshare Terms. If you discover that your use of the service in any way violates such Rideshare Terms, you agree to immediately stop using the Service and notify Car Flo at carln@carflo.co. 
b. You must not copy or capture, or attempt to copy or capture, any content from the Service, unless given express permission by Car Flo.
c. You must not copy, republish, adapt, make available or otherwise communicate to the public, display, perform, transfer, share, distribute or otherwise use or exploit any content on or from the Service, or which is collected by the Service.
d. You must not use any content in any way that is designed to create a separate service or that replicates any part of the offering of the Service.
e. You must not rent, sell or lease access to the Service, or any content available thereon.
f. You must not employ scraping or similar techniques to aggregate, repurpose, republish or otherwise make use of any content.
g. You must not employ any techniques or make use of any services, automated or otherwise, designed to misrepresent your activity on the Service, including without limitation by the use of bots, botnets, scripts, apps, plugins, extensions or other automated means to register accounts, log in, send messages, post comments, or otherwise to act on your behalf, particularly where such activity occurs in a multiple or repetitive fashion. You must not offer or promote the availability of any such techniques or services to any other users of the Service.
h. You must not alter or remove, or attempt to alter or remove, any trademark, copyright or other proprietary or legal notices contained in, or appearing on, the Service or any content appearing on the Service.
i. You must not, and must not permit any third party to, copy or adapt the object code of the Service, or reverse engineer, reverse assemble, decompile, modify or attempt to discover any source or object code of any part of the Service, or circumvent or attempt to circumvent or copy any copy protection mechanism or access any rights management information pertaining to content on the Service.
j. You must not commit or engage in, or encourage, induce, solicit or promote, any conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law or regulation.
k. You must not rent, sell or lease access to the Service, or any content on the Service.
l. You must not deliberately impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity, for example, by registering an account in the name of another person or company, or sending messages or making comments using the name of another person.
m. You must not stalk, exploit, threaten, abuse or otherwise harass another user, or any Car Flo employee. If Car Flo determines that any user has threatened, stalked, harassed, or verbally abused any Car Flo employee or another Car Flo Member, Car Flo reserves the right to immediately terminate that user’s membership and suspend access to the Service. 
n. You must not sell or transfer, or offer to sell or transfer, any Car Flo account to any third party without the prior written approval of Car Flo.
o. You must not collect or attempt to collect personal data, or any other kind of information about other users, including without limitation, through spidering or any form of scraping.
p. You must not violate, circumvent or attempt to violate or circumvent any data security measures employed by Car Flo; access or attempt to access data or materials which are not intended for your use; log into, or attempt to log into, a server or account which you are not authorized to access; attempt to scan or test the vulnerability of Car Flo’s servers, system or network or attempt to breach Car Flo’s data security or authentication procedures; attempt to interfere with the Service by any means including, without limitation, hacking Car Flo’s servers or systems, submitting a virus, overloading, mail-bombing or crashing. Without limitation to any other rights or remedies of Car Flo under these Terms of Use, Car Flo reserves the right to investigate any situation that appears to involve any of the above, and may report such matters to, and cooperate with, appropriate law enforcement authorities in prosecuting any users who have participated in any such violations.

You agree to comply with the above conditions, and acknowledge and agree that Car Flo has the right, in its sole discretion, to terminate your account or take such other action as we see fit if you breach any of the above conditions or any of the other terms of these Terms of Use. This may include taking court action and/or reporting offending users to the relevant authorities.

8. You Bear Risk of Upload. Car Flo uses reasonable security measures in order to attempt to protect any content or information that you upload, including without limitation any information, photographs or other images, or intellectual property (collectively, “Your Content”). However, Car Flo cannot guarantee that there will be no unauthorized copying or distribution of Your Content nor will Car Flo be liable for any copying or usage of Your Content not authorized by Car Flo. You hereby release and forever waive any claims you may have against Car Flo for any such unauthorized copying or usage of Your Content, under any theory of liability. THE SECURITY MEASURES TO PROTECT YOUR CONTENT USED BY CAR FLO HEREIN ARE PROVIDED AND USED "AS-IS" AND WITH NO WARRANTIES OR ASSURANCES THAT SUCH SECURITY MEASURES WILL WITHSTAND ATTEMPTS TO EVADE SECURITY MECHANISMS OR THAT THERE WILL BE NO CRACKS, DISABLEMENTS OR OTHER CIRCUMVENTION OF SUCH SECURITY MEASURES.

Car Flo may, in our sole discretion, remove any content posted on the Service, for any reason or no reason whatsoever. Notwithstanding the foregoing, we are not obligated to monitor content uploaded to the Service and we do not guarantee that we will remove any content that violates these Terms of Use or is illegal or otherwise objectionable. 

9. Payments on the Service. 

Pursuant to the terms of Sections 21 and 22  of this Agreement, you are fully and solely responsible for any damages that arise as a result of your use of the Service, including without limitation traffic or parking tickets or third-party damages for property damage or personal injury. In some cases, you may be able to pay for such damages on the Service. In those cases, the terms of your payment may be determined by agreements between you and the financial institution or other provider of your chosen payment provider (your “Payment Method”). You agree to make payment using that selected Payment Method. Car Flo reserves the right to correct any errors or mistakes that it makes even if it has already requested or received payment.

10. No Employment or Agency Relationship.
You acknowledge and agree that these Terms of Use, and the Privacy Policy, do not create any employment, agency, partnership, or joint venture relationship between you and Car Flo. You are an independent contractor of Car Flo. Nothing contained in these Terms shall be construed to create the relationship of employer and employee, principal and agent, partnership or joint venture, or any other fiduciary relationship. You shall have no authority to act as agent for, or on behalf of, Car Flo, or to represent Car Flo, or bind Car Flo in any manner. You shall not be entitled to worker's compensation, retirement, insurance, unemployment benefits, or any other benefits typically afforded to employees of a company. Car Flo shall not be responsible for federal, state and local taxes derived from your net income or for the withholding and/or payment of any federal, state and local income and other payroll taxes, workers' compensation, disability benefits or other legal requirements applicable to you. You are solely responsible for, and will file on a timely basis, all tax returns and payments required to be filed with, or made to, any federal, state or municipal tax authority with respect to the performance of services and receipt of fees under these Terms. Car Flo will regularly report amounts paid to you to any applicable federal, state, and municipal tax authorities.

11. Modifications to Service, Termination of Service. Car Flo reserves the right at any time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Car Flo shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.

12. Blocking of IP Addresses. In order to protect the integrity of the Service, Car Flo reserves the right at any time in its sole discretion to block Members from certain IP addresses from accessing the Service. 

13. Term. This Terms of Use will remain in full force and effect while you use the Service. You may terminate your membership at any time by emailing us at carln@carflo.co. If you resign or cancel your membership to Car Flo, to help Car Flo analyze and improve the Service, you may be asked to provide a reason for your resignation/cancellation. 

Car Flo may terminate your membership for any reason by sending notice to you at the email address you provide in your application for membership, or such other email address as you may later provide to Car Flo. All decisions regarding the termination of accounts shall be made in the sole discretion of Car Flo. Car Flo is not required to provide you notice prior to terminating your membership. Car Flo is not required, and may be prohibited, from disclosing a reason for the termination of your account. Even after your membership is terminated, this Terms of Use will remain in effect. All terms that by their nature may survive termination of this Terms of Use shall be deemed to survive such termination.

14. Third Party Content. Car Flo may provide third party content on the Service and may provide links to webpages and content of third parties (collectively, the “Third-Party Content”) as a service to those interested in this information. Car Flo does not control, endorse or adopt any Third-Party Content and makes no representation or warranties of any kind regarding the Third-Party Content, including without limitation regarding its accuracy or completeness. Please be aware that Car Flo does not create Third-Party Content, nor does Car Flo update or monitor it. Car Flo is therefore not responsible for any Third-Party Content on the Service. Members use such Third-Party Content at their own risk.

The Service may include links or references to other web sites or services solely as a convenience to Car Flo users (collectively, the “Reference Sites”). Car Flo does not endorse any Reference Sites or the information, materials, products, or services contained on or accessible through Reference Sites. In addition, your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Service are solely between you and the relevant advertiser. Access and use of Reference Sites, including the information, materials, products, and services on or available through Reference Sites is solely at your own risk.

15. Intellectual Property. Car Flo, the Car Flo logos and any other product or service name or slogan contained in the Service are trademarks of Car Flo or our suppliers or licensors and may not be copied, imitated or used, in whole or in part, without the prior written permission of Car Flo or the applicable trademark holder. Any authorized use of these trademarks must be in accordance with any guidelines that Car Flo may provide you from time to time.

Car Flo retains all proprietary rights in the Service, except where otherwise noted. The Service contains the copyrighted material, trademarks, and other proprietary information of Car Flo, and its licensors. Except where we have given you express written permission, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. All content on Car Flo is proprietary. Except where otherwise specified in this Agreement, all content is copyrighted material of Car Flo and for Car Flo Members' use only. Distribution of content to others is strictly prohibited. You agree that Car Flo would be irreparably harmed by any violation or threatened violation of this section and that, therefore, Car Flo shall be entitled to an injunction prohibiting you from any violation or threatened violation of this section, without posting bond, in addition to any other right or remedy it may have.

We may provide links to third party websites, and some of the content appearing on Car Flo may be supplied by third parties. Car Flo has no responsibility for these third party websites nor for their content, which is subject to and governed by the terms of use and/or privacy policies, if any, of the applicable third party content providers.

You may not use any metatags or any other hidden text utilizing “Car Flo” or any other name, trademark or product or service name of Car Flo without our prior written permission. In addition, the look and feel of the Car Flo Service, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of Car Flo and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and company names or logos mentioned in the Service are the property of their respective owners. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise, including without limitation any Rideshare Service, does not constitute or imply endorsement, sponsorship or recommendation thereof by us or any other affiliation.

The Service is owned and operated by Car Flo. Unless otherwise indicated, all content and other materials on the Service, including, without limitation, Car Flo’s logos, the visual interfaces, graphics, design, compilation, information, software, computer code (including source code or object code), services, text, pictures, information, data, sound files, other files and the selection and arrangement thereof (collectively, the “Materials”) are protected by United States copyright, trade dress, patent, and trademark laws, international conventions, and all other relevant intellectual property and proprietary rights, and applicable laws (including in your country of residence). 

16. Ownership of Your Content; Licenses.

Car Flo does not claim ownership of Your Content. However, with respect to Your Content, you grant Car Flo a worldwide, royalty-free, irrevocable, and non-exclusive license(s) to use, publish, distribute, modify, reproduce, sell, and publicly display such content on the Service or elsewhere, for any purpose whatsoever including without limitation monetary gain. 

In the event that you send any unsolicited ideas, suggestions, or feedback to Car Flo (collectively, the “Feedback”), you acknowledge and agree that such Feedback is non-confidential and non-proprietary to you, and you grant to Car Flo a worldwide, royalty-free and non-exclusive license(s) to use, distribute, reproduce, and publicly display such Feedback for any reason or purpose, without attribution or compensation to you. 

17. Copyright Policy. Car Flo prohibits the submission or posting of any information that infringes or violates the copyright rights and/or other intellectual property rights (including rights of privacy and publicity) of any person or entity.

Pursuant to Title 17, United States Code, Section 512(c)(2) or for any other claim of copyright infringement, you hereby agree that notifications of claimed copyright infringement be sent by certified mail to:

2245 Legion Street, Bellmore, NY 11710

When contacting us, please make sure that you include the following information:
a. a statement that you have identified content on Car Flo that infringes your copyright or the copyright of a third party on whose behalf you are entitled to act;
b. a description of the copyright work(s) that you claim have been infringed;
c. a description of the content that you claim is infringing and the Car Flo URL(s) where such content can be located;
d. your full name, address and telephone number, a valid email address on which you can be contacted, and your Car Flo user name if you have one;
e. a statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright owner, its agent, or the law; and
f. a statement by you that the information in your notice is accurate and that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.

In addition, if you wish for your notice to be considered as a notice pursuant to the United States Digital Millennium Copyright Act 17 U.S.C. ¤512(c), please also include the following:

g. with respect to your statement that you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed, confirmation that such statement is made under penalty of perjury; and
h. your electronic or physical signature (which may be a scanned copy).

Car Flo will process any notice of alleged infringement which it receives and will take appropriate action as required by the Digital Millennium Copyright Act (DMCA) 17 U.S.C. 512(c)(3) or other applicable copyright law. U.S. law provides significant penalties for submitting such a statement falsely. Under appropriate circumstances, persons who repeatedly submit infringing or unlawful material will be prohibited from posting further submissions.

The foregoing process applies to copyright only. If you discover any content that you believe to be in violation of your trademark rights, please report this to us by mail or email at 2245 Legion Street, Bellmore, NY 11710 or carln@carflo.co. In all other cases, if you discover content that infringes any or violates any of your other rights, which you believe is defamatory, pornographic, obscene, racist or otherwise liable to cause widespread offence, or which constitutes impersonation, harassment, spam or otherwise violates these Terms of Use or applicable law, please report this to us at 2245 Legion Street, Bellmore, NY 11710 or carln@carflo.co.

18. Repeat Infringer Policy. Car Flo has adopted a policy that it will promptly terminate without notice any user's access to the Service if that user is determined by Car Flo to be a "repeat infringer." A repeat infringer includes, without limitation a user who has been notified by Car Flo of infringing activity violations more than twice. Car Flo may also at our sole discretion limit access to the Service and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.
	
19. Repeat Infringer Policy. In accordance with the DMCA and other applicable laws around the world, Car Flo has adopted a policy that it will promptly terminate without notice any user's access to the Service if that user is determined by Car Flo to be a "repeat infringer." A repeat infringer includes, without limitation, a user who has been notified by Car Flo of infringing activity violations more than twice and/or who has had any user-submitted content removed from the Service more than twice. Car Flo may also at our sole discretion limit access to the Service and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.

In addition, Car Flo accommodates and does not interfere with standard technical measures used by intellectual property rights owners to protect their materials.

Please note that we do not offer refunds to Members whose accounts are terminated as a result of repeated infringement of these Terms of Use.

20. Terms for the iOS App
 You acknowledge and agree that this Terms of Use is between you and Car Flo only, and that Apple is not a party to these Terms of Use. Car Flo, not Apple, is responsible for the App and its contents. 

You must not use the iOS App except on an Apple-branded product that is running iOS. Any use of the App by you must comply with the relevant terms of use for the Apple Source from which you obtained it (including, without limitation, the Usage Rules set forth in the Apple App Store Terms of Service). You acknowledge and agree that Apple does not have any obligation to furnish you with maintenance and/or support services with respect to the App.

You further acknowledge and agree that Apple is not responsible for addressing or resolving any claims by you or a third party relating to your use and/or possession of the App, including, but not limited to, warranty or liability claims, claims that the App fails to conform to a legal or regulatory requirement, consumer protection or similar claims, or claims that the App infringes the intellectual property rights of a third party (including, without limitation, trademark, copyright, and/or patent rights).
 Any claims, losses, liabilities, damages costs or expenses relating to a failure to conform to any warranty shall be Car Flo’s responsibility, to the extent allowable by these Terms of Use. It is important that you read the entire Terms of Use, as other sections of these Terms of Use limit our liability.
 Apple and its subsidiaries are third-party beneficiaries of these Terms of Use. By accepting these Terms of Use, you acknowledge and agree that Apple shall have the right (and will be deemed to have accepted that right) to enforce the Terms of Use against you as a third party beneficiary. Apple is the sole third party beneficiary and there are no other third-party beneficiaries of the Terms.

21. Limitation of Liability. In no event shall Car Flo be liable for any damages whatsoever, whether direct, indirect, general, special, compensatory, consequential, and/or incidental, arising out of or relating to the Service, or use thereof. Nothing contained in the Service or in any written or oral communications from Car Flo or its employees or agents shall be construed to make any promise, covenant, warranty, or guaranty, all of which are explicitly disclaimed hereby, contrary to the statements and disclaimers contained in this paragraph.

The content and functionality on the Service, along with the services provided by employees of the Service, are offered "as is" without warranty of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. Car Flo makes no warranties, express or implied, as to the ownership, accuracy, completeness or adequacy of the Service’s content or that the functionality of the Service will be uninterrupted or error-free or free from virus or third party attack. You hereby acknowledge that your use of the Service is at your sole risk. UNDER NO CIRCUMSTANCES SHALL CAR FLO, ITS OFFICERS, OWNERS, EMPLOYEES OR AGENTS AND THEIR RESPECTIVE HEIRS, SUCCESSORS AND ASSIGNS BE LIABLE FOR ANY DAMAGES, INCLUDING DIRECT, INCIDENTAL, PUNITIVE, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES THAT DIRECTLY OR INDIRECTLY RESULT FROM USE OF, OR INABILITY TO USE, THE SERVICE OR THE INFORMATION CONTAINED THEREON, INCLUDING WITHOUT LIMITATION FOR VIRUSES ALLEGED TO HAVE BEEN OBTAINED FROM THE SERVICE, EVEN IF CAR FLO HAS BEEN NOTIFIED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES AND REGARDLESS OF THE THEORY OF LIABILITY.

TO THE GREATEST EXTENT PERMITTED BY LAW, YOU AGREE THAT IN NO EVENT WILL CAR FLO HAVE ANY LIABILITY, CONTINGENT OR OTHERWISE, FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES IN ANY WAY ARISING OUT OF OR RELATING TO THE AGREEMENT OR THE SERVICE, INCLUDING, BUT NOT LIMITED TO PERSONAL INJURY, DEATH, PROPERTY DAMAGE, TRAFFIC OR PARKING TICKETS, LOST PROFITS, LOST DATA, LOSS OF GOODWILL, COPYRIGHT INFRINGEMENT, WORK STOPPAGE, EQUIPMENT FAILURE OR MALFUNCTION, OR ANY OTHER DAMAGES OR LOSSES, EVEN IF CAR FLO HAS BEEN ADVISED OF THE POSSIBILITY THEREOF, AND REGARDLESS OF THE LEGAL OR EQUITABLE THEORY (CONTRACT, TORT, STATUTE, INDEMNITY OR OTHERWISE) UPON WHICH SUCH LIABILITY IS BASED.

YOU FURTHER ACKNOWLEDGE AND AGREE THAT CAR FLO SHALL HAVE NO LIABILITY FOR DAMAGES ARISING FROM ANY DISPUTE BETWEEN YOURSELF AND ANOTHER USER OF THE SERVICE.

In the event that any of the foregoing limitations are deemed to be unenforceable, to the greatest extent permitted by law, you agree that the entire aggregate liability of Car Flo and sole remedy available to any Member in any case in any way arising out of or relating to the Agreement or the Service shall be limited to monetary damages that in the aggregate may not exceed $500.00.

22. Indemnity by You. You agree to indemnify and hold Car Flo, its subsidiaries, affiliates, officers, agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorneys' fees, arising out of or related to:

a. your use of the Service in violation of this Terms of Use and/or arising from a breach of this Terms of Use including without limitation your representations and warranties set forth above;
b. any third-party actions relating to your use of the Service, including without limitation actions for personal injury, death, or property damage; or
c. Your violation of any Rideshare Terms, or your use of the Service in violation thereof. 

23. Attorney Fees. In the event that Car Flo is successful in whole or in part in any action or proceeding related to or arising from this Terms of Use, you shall be responsible for Car Flo’s attorneys' fees and costs.

24. Parental or Guardian Permission. Some of the content on the Service may not be appropriate for children. CHILDREN UNDER THE AGE OF 18 ARE NOT PERMITTED TO USE THE SERVICE UNLESS A SUPERVISING PARENT OR GUARDIAN IS PRESENT. INDIVIDUALS UNDER THE AGE OF 18 ARE NOT PERMITTED TO SUBSCRIBE TO OUR SERVICE OR GIVE CAR FLO THEIR EMAIL ADDRESS OR ANY OTHER PERSONALLY IDENTIFIABLE INFORMATION.

25. Jurisdiction and Choice of Law; Dispute Resolution. If there is any dispute arising out of the Service, by using the Service, you expressly agree that any such dispute shall be governed by the laws of the State of New York, without regard to its conflict of law provisions, and you expressly agree and consent to the exclusive jurisdiction and venue of the state and federal courts of the State of New York, for the resolution of any such dispute. Acceptance of the terms and conditions of this Agreement constitutes your consent to be sued in such courts and to accept service of process outside the State of New York with the same force and effect as if such service had been made within the State of New York. You hereby agree to accept service of process for any action hereunder by certified mail return receipt requested which service shall have the same force and effect as though service had been effected by personal service in the applicable jurisdiction. If any part of these terms is unlawful, void, or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of the remaining provisions.

26. Arbitration Provision/No Class Action. Except where prohibited by law, as a condition of using the Service, you agree that any and all disputes, claims and causes of action (collectively, "Claim") arising out of or connected with the Service, shall be resolved individually, without resort to any form of class action, exclusively by binding arbitration for full and final settlement of such Claim, and judgment on the award rendered in the arbitration may be entered in any court having jurisdiction thereof. The parties shall split the arbitration and/or mediator costs. An award rendered by the arbitrator(s) may be entered and confirmed by the courts of the State of New York, County of Nassau, or the United States District Court for the Eastern District of New York. The parties agree that any post-arbitration action seeking to enforce an arbitration award or action seeking equitable or injunctive relief shall be brought exclusively in the courts of the State of New York, County of Nassau, or the United States District Court for the Eastern District of New York.

27. No Third Party Beneficiaries. You agree that, except as otherwise expressly provided in this Terms of Use, there shall be no third party beneficiaries to this Terms of Use.

28. Availability Outside the U.S. If you access Car Flo from outside of the United States, you do so at your own risk and are responsible for compliance with the laws of your jurisdiction. If you access the Service from outside of the United States, you acknowledge that any personal information you provide will be processed in the United States and other geographies as selected by us in our sole discretion, and you hereby consent to the collection and processing of your personal information in a manner consistent with this Agreement the Car Flo Privacy Policy.

29. Entire Agreement. This Terms of Use, along with the Car Flo Privacy Policy, contains the entire agreement between you and Car Flo regarding the use of the Service.

30. Severability; Waiver. If any provision of this Terms of Use is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Terms of Use, which shall remain in full force and effect. No waiver of any term of this Terms of Use shall be deemed a further or continuing waiver of such term or any other term. In addition, Car Flo’s failure to enforce any term of this Terms of Use shall not be deemed as a waiver of such term or otherwise affect Car Flo’s ability to enforce such term at any point in the future.

31. Headings. The section headings contained in this Terms of Use are for reference purposes only and shall not in any way affect the meaning or interpretation of this Terms of Use.

Please contact us with any questions regarding this agreement. Car Flo is a trademark of Car Flo.

Car Flo reserves all rights not expressly granted in these Terms of Use.

I HAVE READ THIS AGREEMENT AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE.`

export const PRIVACY_POLICY = `Of all of the celestial bodies that capture our attention and fascination as astronomers, none has a greater influence on life on planet Earth than it’s own satellite, the moon. When you think about it, we regard the moon with such powerful significance that unlike the moons of other planets which we give names, we only refer to our one and only orbiting orb as THE moon. It is not a moon. To us, it is the one and only moon.

The moon works its way into our way of thinking, our feelings about romance, our poetry and literature and even how we feel about our day in day out lives in many cases. It is not only primitive societies that ascribe mood swings, changes in social conduct and changes in weather to the moon. Even today, a full moon can have a powerful effect on these forces which we acknowledge even if we cannot explain them scientifically.

The most obvious physical phenomenon that is directly affected by the gravity of the moon are the tides of the ocean. The tides are an integral part of how maritime life is regulated and the comings and goings of the fishing world in coastal communities. But not very many people know that at certain times of the year when the orbits of the earth bring the sun and moon into right alignment, there can even be tidal effect on inland bodies of water and even on the solid earth. Eons ago, when the moon’s orbit was closer to the Earth, it was the effect of the moon that caused massive changes in the topography of the land and on continental drift as well. This reflects the powerful effect the moon has had on both human history and on global geographical history as well.

You may sometimes wonder where the moon came from. Was it a planet that traveled too close to Earth and was captured in our orbit? Actually, the prevailing theory of modern science is that the moon was the result of a large scale collision with the still developing Earth early in its development which caused this large “chuck” to spin off into an orbiting body. This explains the similarity in composition as has been confirmed by many of the moon exploratory space missions that were conducted by NASA.

But this background also highlights another important influence the moon has had on Earth’s development that is seldom recognized and that is the stabilization of Earth’s orbital pattern. Most know that Earth is not round but more of an egg shaped orb. To be blunt, the Earth would wobble. Without the moon’s stabilizing influence, this shape would shift dramatically so the tilt of the axis, that is the polar caps would shift dramatically with each seasonal rotation producing climacteric, changes much more violent and drastic than we are used to. It is possible that life as we know it could not have developed here had the moon not been there to “keep the Earth in line” and continue to stabilize the orbital position of the Earth so our climate could remain stable and mild.

A third significant influence of the moon comes from that origin as coming from a collision which “ripped” the body of the moon from the developing core of the Earth. Because of this disruption in how the core of our planet developed, the metals that are usually intact in the core of the planet are actually scattered up and down the geography of the earth in diverse ways. Usually the metals of the planet are all concentrated deep in the core. But because of the collision which took the moon out to orbit, metals that have been crucial to the development of our industrial and technological cultures are readily available and easy for use to mine. This again, is something we can thank the presence of that lovely moon in the sky for.`
