export const TERMS_CONDITIONS = `For most of us, the idea of astronomy is something we directly connect to “stargazing”, telescopes and seeing magnificent displays in the heavens. And to be sure, that is the exciting area of astronomy that accounts for it’s huge popularity. So to the uninitiated, the idea of “radio astronomy” seems strange. There are two reasons for that. First is that humans are far more visual than audio oriented. And the second is that radio astronomy doesn’t really involve “listening” to the cosmos except to the extent that scientists who use this sophisticated form of “stargazing” do not rely on visual study to conduct their work.

To appreciate what is really exciting about radio astronomy, first we have to shift how we view astronomy. That is because to professional astronomers, studying the universe is more about frequencies than it is about visual documentation of phenomenon. This takes us back to Physics 101.

Light, obviously, is the physical phenomenon that empowers our ability to use our visual confirmation system, e.g. our eyes to appreciate something, in this case the stars. So when we look up at the heavens, we can see the light emitting from a star or reflecting from a planet or moon. In many cases, if we see a far away star, we are actually seeing it hundreds or thousands of years ago because that is how long it takes for that light to cross the universe and be visible in our sky. That alone is a pretty mind blowing idea.

Now light itself is a pretty strange substance. But to our astronomy scientists, light is just another energy that exists in a certain frequency. Now, we tend to think of frequencies when we talk about sound waves. In scientific terms light, energy and sound are just a few forms of the same thing, frequencies of energy that are emulating from a source.

Now we get to why radio astronomy is so necessary. The range of frequency that light occupies in the big spectrum of frequencies is really pretty small. To put that more bluntly, we can only “see” a tiny part of the universe that is actually there. Now when you look up in the night sky and it is so overwhelming, when you then that we are seeing just a tiny amount of what is actually going on up there, again, our minds can get pretty overwhelmed.

Radio astronomy uses sophisticated sensor equipment to study ALL of the frequencies of energy coming to us from the cosmos. In that way, these scientists can “see” everything that is going on out there and so get a precise idea of how the stars look, behave now and will behave in the future.

For some of us who have heard about radio astronomy, we think of it in terms of “listening” for signs of life in the universe. And yes, SETI, or “the Search for Extra Terrestrial Intelligence” is a part of radio astronomy, albeit a tiny part. But of much greater importance is how radio astronomy has empowered serious astronomers (that is those who get paid to do it) to study stars many light years away, to study black holes which we could never see with our telescopes and to gather research and data about the whole of the universe that otherwise would be impossible to know and understand.

This is important work that is constantly ongoing in the world of astronomy. It is worth keeping up with and learning more about as we have barely scratched the surface in our brief discussion today. But understanding how important radio astronomy is will only deepen and make more meaningful your love and grasp of this big field of knowledge known as astronomy.`

export const PRIVACY_POLICY = `Of all of the celestial bodies that capture our attention and fascination as astronomers, none has a greater influence on life on planet Earth than it’s own satellite, the moon. When you think about it, we regard the moon with such powerful significance that unlike the moons of other planets which we give names, we only refer to our one and only orbiting orb as THE moon. It is not a moon. To us, it is the one and only moon.

The moon works its way into our way of thinking, our feelings about romance, our poetry and literature and even how we feel about our day in day out lives in many cases. It is not only primitive societies that ascribe mood swings, changes in social conduct and changes in weather to the moon. Even today, a full moon can have a powerful effect on these forces which we acknowledge even if we cannot explain them scientifically.

The most obvious physical phenomenon that is directly affected by the gravity of the moon are the tides of the ocean. The tides are an integral part of how maritime life is regulated and the comings and goings of the fishing world in coastal communities. But not very many people know that at certain times of the year when the orbits of the earth bring the sun and moon into right alignment, there can even be tidal effect on inland bodies of water and even on the solid earth. Eons ago, when the moon’s orbit was closer to the Earth, it was the effect of the moon that caused massive changes in the topography of the land and on continental drift as well. This reflects the powerful effect the moon has had on both human history and on global geographical history as well.

You may sometimes wonder where the moon came from. Was it a planet that traveled too close to Earth and was captured in our orbit? Actually, the prevailing theory of modern science is that the moon was the result of a large scale collision with the still developing Earth early in its development which caused this large “chuck” to spin off into an orbiting body. This explains the similarity in composition as has been confirmed by many of the moon exploratory space missions that were conducted by NASA.

But this background also highlights another important influence the moon has had on Earth’s development that is seldom recognized and that is the stabilization of Earth’s orbital pattern. Most know that Earth is not round but more of an egg shaped orb. To be blunt, the Earth would wobble. Without the moon’s stabilizing influence, this shape would shift dramatically so the tilt of the axis, that is the polar caps would shift dramatically with each seasonal rotation producing climacteric, changes much more violent and drastic than we are used to. It is possible that life as we know it could not have developed here had the moon not been there to “keep the Earth in line” and continue to stabilize the orbital position of the Earth so our climate could remain stable and mild.

A third significant influence of the moon comes from that origin as coming from a collision which “ripped” the body of the moon from the developing core of the Earth. Because of this disruption in how the core of our planet developed, the metals that are usually intact in the core of the planet are actually scattered up and down the geography of the earth in diverse ways. Usually the metals of the planet are all concentrated deep in the core. But because of the collision which took the moon out to orbit, metals that have been crucial to the development of our industrial and technological cultures are readily available and easy for use to mine. This again, is something we can thank the presence of that lovely moon in the sky for.`
